#pragma once

#include <gdt/assume.hxx>
#include <cstddef>

namespace gdt
{
    // Vector.
    template<typename T, std::size_t N> struct vec;
    template<typename T> using vec2 = vec<T, 2>;
    template<typename T> using vec3 = vec<T, 3>;
    template<typename T> using vec4 = vec<T, 4>;

    // Vector.
    template<typename T, std::size_t N>
    struct vec
    {
    public:
        // Constructor.
        constexpr vec() = default;

        // Constructor.
        constexpr vec(const T& x, const T& y)
        requires (N == 2)
        :
            _data{x, y}
        {}

        // Constructor.
        constexpr vec(const T& x, const T& y, const T& z)
        requires (N == 3)
        :
            _data{x, y, z}
        {}

        // Constructor.
        constexpr vec(const T& x, const vec2<T>& yz)
        requires (N == 3)
        :
            _data{x, yz[0], yz[1]}
        {}

        // Constructor.
        constexpr vec(const vec2<T>& xy, const T& z)
        requires (N == 3)
        :
            _data{xy[0], xy[1], z}
        {}

        // Constructor.
        constexpr vec(const T& x, const T& y, const T& z, const T& w)
        requires (N == 4)
        :
            _data{x, y, z, w}
        {}

        // Constructor.
        constexpr vec(const T& x, const T& y, const vec2<T>& zw)
        requires (N == 4)
        :
            _data{x, y, zw[0], zw[1]}
        {}

        // Constructor.
        constexpr vec(const T& x, const vec2<T>& yz, const T& w)
        requires (N == 4)
        :
            _data{x, yz[0]. yz[1], w}
        {}

        // Constructor.
        constexpr vec(const vec2<T>& xy, const T& z, const T& w)
        requires (N == 4)
        :
            _data{xy[0], xy[1], z, w}
        {}

        // Constructor.
        constexpr vec(const vec2<T>& xy, const vec2<T>& zw)
        requires (N == 4)
        :
            _data{xy[0], xy[1], zw[0], zw[1]}
        {}

        // Constructor.
        constexpr vec(const T& x, const vec3<T>& yzw)
        requires (N == 4)
        :
            _data{x, yzw[0], yzw[1], yzw[2]}
        {}

        // Constructor.
        constexpr vec(const vec3<T>& xyz, const T& w)
        requires (N == 4)
        :
            _data{xyz[0], xyz[1], xyz[2], w}
        {}

        // Constructor.
        template<typename OtherT, std::size_t OtherN>
        explicit constexpr vec(const vec<OtherT, OtherN>& other)
        requires (OtherN >= N)
        {
            for (std::size_t i = 0; i < N; ++i)
            {
                _data[i] = T(other[i]);
            }
        }

        // Subscript.
        constexpr T& operator[](std::size_t i)
        {
            gdt_assume(i <= N);
            return _data[i];
        }

        // Subscript.
        constexpr const T& operator[](std::size_t i) const
        {
            gdt_assume(i <= N);
            return _data[i];
        }

        #define gdt(i, I)\
        constexpr T& i() requires (N > I)\
        {\
            return _data[I];\
        }\
        constexpr const T& i() const requires (N > I)\
        {\
            return _data[I];\
        }
        gdt(x, 0)
        gdt(y, 1)
        gdt(z, 2)
        gdt(w, 3)
        gdt(r, 0)
        gdt(g, 1)
        gdt(b, 2)
        gdt(a, 3)
        #undef gdt

        #define gdt(i, j, MinN)\
        constexpr vec2<T> i##j() const requires (N >= MinN)\
        {\
            return {i(), j()};\
        }
        gdt(x, x, 1)
        gdt(x, y, 2)
        gdt(x, z, 3)
        gdt(x, w, 4)
        gdt(y, x, 2)
        gdt(y, y, 2)
        gdt(y, z, 3)
        gdt(y, w, 4)
        gdt(z, x, 3)
        gdt(z, y, 3)
        gdt(z, z, 3)
        gdt(z, w, 4)
        gdt(w, x, 4)
        gdt(w, y, 4)
        gdt(w, z, 4)
        gdt(w, w, 4)
        gdt(r, r, 1)
        gdt(r, g, 2)
        gdt(r, b, 3)
        gdt(r, a, 4)
        gdt(g, r, 2)
        gdt(g, g, 2)
        gdt(g, b, 3)
        gdt(g, a, 4)
        gdt(b, r, 3)
        gdt(b, g, 3)
        gdt(b, b, 3)
        gdt(b, a, 4)
        gdt(a, r, 4)
        gdt(a, g, 4)
        gdt(a, b, 4)
        gdt(a, a, 4)
        #undef gdt

        #define gdt(i, j, k, MinN)\
        constexpr vec3<T> i##j##k() const requires (N >= MinN)\
        {\
            return {i(), j(), k()};\
        }
        gdt(x, x, x, 1)
        gdt(x, x, y, 2)
        gdt(x, x, z, 3)
        gdt(x, x, w, 4)
        gdt(x, y, x, 2)
        gdt(x, y, y, 2)
        gdt(x, y, z, 3)
        gdt(x, y, w, 4)
        gdt(x, z, x, 3)
        gdt(x, z, y, 3)
        gdt(x, z, z, 3)
        gdt(x, z, w, 4)
        gdt(x, w, x, 4)
        gdt(x, w, y, 4)
        gdt(x, w, z, 4)
        gdt(x, w, w, 4)
        gdt(y, x, x, 2)
        gdt(y, x, y, 2)
        gdt(y, x, z, 3)
        gdt(y, x, w, 4)
        gdt(y, y, x, 2)
        gdt(y, y, y, 2)
        gdt(y, y, z, 3)
        gdt(y, y, w, 4)
        gdt(y, z, x, 3)
        gdt(y, z, y, 3)
        gdt(y, z, z, 3)
        gdt(y, z, w, 4)
        gdt(y, w, x, 4)
        gdt(y, w, y, 4)
        gdt(y, w, z, 4)
        gdt(y, w, w, 4)
        gdt(z, x, x, 3)
        gdt(z, x, y, 3)
        gdt(z, x, z, 3)
        gdt(z, x, w, 4)
        gdt(z, y, x, 3)
        gdt(z, y, y, 3)
        gdt(z, y, z, 3)
        gdt(z, y, w, 4)
        gdt(z, z, x, 3)
        gdt(z, z, y, 3)
        gdt(z, z, z, 3)
        gdt(z, z, w, 4)
        gdt(z, w, x, 4)
        gdt(z, w, y, 4)
        gdt(z, w, z, 4)
        gdt(z, w, w, 4)
        gdt(w, x, x, 4)
        gdt(w, x, y, 4)
        gdt(w, x, z, 4)
        gdt(w, x, w, 4)
        gdt(w, y, x, 4)
        gdt(w, y, y, 4)
        gdt(w, y, z, 4)
        gdt(w, y, w, 4)
        gdt(w, z, x, 4)
        gdt(w, z, y, 4)
        gdt(w, z, z, 4)
        gdt(w, z, w, 4)
        gdt(w, w, x, 4)
        gdt(w, w, y, 4)
        gdt(w, w, z, 4)
        gdt(w, w, w, 4)
        gdt(r, r, r, 1)
        gdt(r, r, g, 2)
        gdt(r, r, b, 3)
        gdt(r, r, a, 4)
        gdt(r, g, r, 2)
        gdt(r, g, g, 2)
        gdt(r, g, b, 3)
        gdt(r, g, a, 4)
        gdt(r, b, r, 3)
        gdt(r, b, g, 3)
        gdt(r, b, b, 3)
        gdt(r, b, a, 4)
        gdt(r, a, r, 4)
        gdt(r, a, g, 4)
        gdt(r, a, b, 4)
        gdt(r, a, a, 4)
        gdt(g, r, r, 2)
        gdt(g, r, g, 2)
        gdt(g, r, b, 3)
        gdt(g, r, a, 4)
        gdt(g, g, r, 2)
        gdt(g, g, g, 2)
        gdt(g, g, b, 3)
        gdt(g, g, a, 4)
        gdt(g, b, r, 3)
        gdt(g, b, g, 3)
        gdt(g, b, b, 3)
        gdt(g, b, a, 4)
        gdt(g, a, r, 4)
        gdt(g, a, g, 4)
        gdt(g, a, b, 4)
        gdt(g, a, a, 4)
        gdt(b, r, r, 3)
        gdt(b, r, g, 3)
        gdt(b, r, b, 3)
        gdt(b, r, a, 4)
        gdt(b, g, r, 3)
        gdt(b, g, g, 3)
        gdt(b, g, b, 3)
        gdt(b, g, a, 4)
        gdt(b, b, r, 3)
        gdt(b, b, g, 3)
        gdt(b, b, b, 3)
        gdt(b, b, a, 4)
        gdt(b, a, r, 4)
        gdt(b, a, g, 4)
        gdt(b, a, b, 4)
        gdt(b, a, a, 4)
        gdt(a, r, r, 4)
        gdt(a, r, g, 4)
        gdt(a, r, b, 4)
        gdt(a, r, a, 4)
        gdt(a, g, r, 4)
        gdt(a, g, g, 4)
        gdt(a, g, b, 4)
        gdt(a, g, a, 4)
        gdt(a, b, r, 4)
        gdt(a, b, g, 4)
        gdt(a, b, b, 4)
        gdt(a, b, a, 4)
        gdt(a, a, r, 4)
        gdt(a, a, g, 4)
        gdt(a, a, b, 4)
        gdt(a, a, a, 4)
        #undef gdt

        #define gdt(i, j, k, l, MinN)\
        constexpr vec3<T> i##j##k##l() const requires (N >= MinN)\
        {\
            return {i(), j(), k(), l()};\
        }
        gdt(x, x, x, x, 1)
        gdt(x, x, x, y, 2)
        gdt(x, x, x, z, 3)
        gdt(x, x, x, w, 4)
        gdt(x, x, y, x, 2)
        gdt(x, x, y, y, 2)
        gdt(x, x, y, z, 3)
        gdt(x, x, y, w, 4)
        gdt(x, x, z, x, 3)
        gdt(x, x, z, y, 3)
        gdt(x, x, z, z, 3)
        gdt(x, x, z, w, 4)
        gdt(x, x, w, x, 4)
        gdt(x, x, w, y, 4)
        gdt(x, x, w, z, 4)
        gdt(x, x, w, w, 4)
        gdt(x, y, x, x, 2)
        gdt(x, y, x, y, 2)
        gdt(x, y, x, z, 3)
        gdt(x, y, x, w, 4)
        gdt(x, y, y, x, 2)
        gdt(x, y, y, y, 2)
        gdt(x, y, y, z, 3)
        gdt(x, y, y, w, 4)
        gdt(x, y, z, x, 3)
        gdt(x, y, z, y, 3)
        gdt(x, y, z, z, 3)
        gdt(x, y, z, w, 4)
        gdt(x, y, w, x, 4)
        gdt(x, y, w, y, 4)
        gdt(x, y, w, z, 4)
        gdt(x, y, w, w, 4)
        gdt(x, z, x, x, 3)
        gdt(x, z, x, y, 3)
        gdt(x, z, x, z, 3)
        gdt(x, z, x, w, 4)
        gdt(x, z, y, x, 3)
        gdt(x, z, y, y, 3)
        gdt(x, z, y, z, 3)
        gdt(x, z, y, w, 4)
        gdt(x, z, z, x, 3)
        gdt(x, z, z, y, 3)
        gdt(x, z, z, z, 3)
        gdt(x, z, z, w, 4)
        gdt(x, z, w, x, 4)
        gdt(x, z, w, y, 4)
        gdt(x, z, w, z, 4)
        gdt(x, z, w, w, 4)
        gdt(x, w, x, x, 4)
        gdt(x, w, x, y, 4)
        gdt(x, w, x, z, 4)
        gdt(x, w, x, w, 4)
        gdt(x, w, y, x, 4)
        gdt(x, w, y, y, 4)
        gdt(x, w, y, z, 4)
        gdt(x, w, y, w, 4)
        gdt(x, w, z, x, 4)
        gdt(x, w, z, y, 4)
        gdt(x, w, z, z, 4)
        gdt(x, w, z, w, 4)
        gdt(x, w, w, x, 4)
        gdt(x, w, w, y, 4)
        gdt(x, w, w, z, 4)
        gdt(x, w, w, w, 4)
        gdt(y, x, x, x, 2)
        gdt(y, x, x, y, 2)
        gdt(y, x, x, z, 3)
        gdt(y, x, x, w, 4)
        gdt(y, x, y, x, 2)
        gdt(y, x, y, y, 2)
        gdt(y, x, y, z, 3)
        gdt(y, x, y, w, 4)
        gdt(y, x, z, x, 3)
        gdt(y, x, z, y, 3)
        gdt(y, x, z, z, 3)
        gdt(y, x, z, w, 4)
        gdt(y, x, w, x, 4)
        gdt(y, x, w, y, 4)
        gdt(y, x, w, z, 4)
        gdt(y, x, w, w, 4)
        gdt(y, y, x, x, 2)
        gdt(y, y, x, y, 2)
        gdt(y, y, x, z, 3)
        gdt(y, y, x, w, 4)
        gdt(y, y, y, x, 2)
        gdt(y, y, y, y, 2)
        gdt(y, y, y, z, 3)
        gdt(y, y, y, w, 4)
        gdt(y, y, z, x, 3)
        gdt(y, y, z, y, 3)
        gdt(y, y, z, z, 3)
        gdt(y, y, z, w, 4)
        gdt(y, y, w, x, 4)
        gdt(y, y, w, y, 4)
        gdt(y, y, w, z, 4)
        gdt(y, y, w, w, 4)
        gdt(y, z, x, x, 3)
        gdt(y, z, x, y, 3)
        gdt(y, z, x, z, 3)
        gdt(y, z, x, w, 4)
        gdt(y, z, y, x, 3)
        gdt(y, z, y, y, 3)
        gdt(y, z, y, z, 3)
        gdt(y, z, y, w, 4)
        gdt(y, z, z, x, 3)
        gdt(y, z, z, y, 3)
        gdt(y, z, z, z, 3)
        gdt(y, z, z, w, 4)
        gdt(y, z, w, x, 4)
        gdt(y, z, w, y, 4)
        gdt(y, z, w, z, 4)
        gdt(y, z, w, w, 4)
        gdt(y, w, x, x, 4)
        gdt(y, w, x, y, 4)
        gdt(y, w, x, z, 4)
        gdt(y, w, x, w, 4)
        gdt(y, w, y, x, 4)
        gdt(y, w, y, y, 4)
        gdt(y, w, y, z, 4)
        gdt(y, w, y, w, 4)
        gdt(y, w, z, x, 4)
        gdt(y, w, z, y, 4)
        gdt(y, w, z, z, 4)
        gdt(y, w, z, w, 4)
        gdt(y, w, w, x, 4)
        gdt(y, w, w, y, 4)
        gdt(y, w, w, z, 4)
        gdt(y, w, w, w, 4)
        gdt(z, x, x, x, 3)
        gdt(z, x, x, y, 3)
        gdt(z, x, x, z, 3)
        gdt(z, x, x, w, 4)
        gdt(z, x, y, x, 3)
        gdt(z, x, y, y, 3)
        gdt(z, x, y, z, 3)
        gdt(z, x, y, w, 4)
        gdt(z, x, z, x, 3)
        gdt(z, x, z, y, 3)
        gdt(z, x, z, z, 3)
        gdt(z, x, z, w, 4)
        gdt(z, x, w, x, 4)
        gdt(z, x, w, y, 4)
        gdt(z, x, w, z, 4)
        gdt(z, x, w, w, 4)
        gdt(z, y, x, x, 3)
        gdt(z, y, x, y, 3)
        gdt(z, y, x, z, 3)
        gdt(z, y, x, w, 4)
        gdt(z, y, y, x, 3)
        gdt(z, y, y, y, 3)
        gdt(z, y, y, z, 3)
        gdt(z, y, y, w, 4)
        gdt(z, y, z, x, 3)
        gdt(z, y, z, y, 3)
        gdt(z, y, z, z, 3)
        gdt(z, y, z, w, 4)
        gdt(z, y, w, x, 4)
        gdt(z, y, w, y, 4)
        gdt(z, y, w, z, 4)
        gdt(z, y, w, w, 4)
        gdt(z, z, x, x, 3)
        gdt(z, z, x, y, 3)
        gdt(z, z, x, z, 3)
        gdt(z, z, x, w, 4)
        gdt(z, z, y, x, 3)
        gdt(z, z, y, y, 3)
        gdt(z, z, y, z, 3)
        gdt(z, z, y, w, 4)
        gdt(z, z, z, x, 3)
        gdt(z, z, z, y, 3)
        gdt(z, z, z, z, 3)
        gdt(z, z, z, w, 4)
        gdt(z, z, w, x, 4)
        gdt(z, z, w, y, 4)
        gdt(z, z, w, z, 4)
        gdt(z, z, w, w, 4)
        gdt(z, w, x, x, 4)
        gdt(z, w, x, y, 4)
        gdt(z, w, x, z, 4)
        gdt(z, w, x, w, 4)
        gdt(z, w, y, x, 4)
        gdt(z, w, y, y, 4)
        gdt(z, w, y, z, 4)
        gdt(z, w, y, w, 4)
        gdt(z, w, z, x, 4)
        gdt(z, w, z, y, 4)
        gdt(z, w, z, z, 4)
        gdt(z, w, z, w, 4)
        gdt(z, w, w, x, 4)
        gdt(z, w, w, y, 4)
        gdt(z, w, w, z, 4)
        gdt(z, w, w, w, 4)
        gdt(w, x, x, x, 4)
        gdt(w, x, x, y, 4)
        gdt(w, x, x, z, 4)
        gdt(w, x, x, w, 4)
        gdt(w, x, y, x, 4)
        gdt(w, x, y, y, 4)
        gdt(w, x, y, z, 4)
        gdt(w, x, y, w, 4)
        gdt(w, x, z, x, 4)
        gdt(w, x, z, y, 4)
        gdt(w, x, z, z, 4)
        gdt(w, x, z, w, 4)
        gdt(w, x, w, x, 4)
        gdt(w, x, w, y, 4)
        gdt(w, x, w, z, 4)
        gdt(w, x, w, w, 4)
        gdt(w, y, x, x, 4)
        gdt(w, y, x, y, 4)
        gdt(w, y, x, z, 4)
        gdt(w, y, x, w, 4)
        gdt(w, y, y, x, 4)
        gdt(w, y, y, y, 4)
        gdt(w, y, y, z, 4)
        gdt(w, y, y, w, 4)
        gdt(w, y, z, x, 4)
        gdt(w, y, z, y, 4)
        gdt(w, y, z, z, 4)
        gdt(w, y, z, w, 4)
        gdt(w, y, w, x, 4)
        gdt(w, y, w, y, 4)
        gdt(w, y, w, z, 4)
        gdt(w, y, w, w, 4)
        gdt(w, z, x, x, 4)
        gdt(w, z, x, y, 4)
        gdt(w, z, x, z, 4)
        gdt(w, z, x, w, 4)
        gdt(w, z, y, x, 4)
        gdt(w, z, y, y, 4)
        gdt(w, z, y, z, 4)
        gdt(w, z, y, w, 4)
        gdt(w, z, z, x, 4)
        gdt(w, z, z, y, 4)
        gdt(w, z, z, z, 4)
        gdt(w, z, z, w, 4)
        gdt(w, z, w, x, 4)
        gdt(w, z, w, y, 4)
        gdt(w, z, w, z, 4)
        gdt(w, z, w, w, 4)
        gdt(w, w, x, x, 4)
        gdt(w, w, x, y, 4)
        gdt(w, w, x, z, 4)
        gdt(w, w, x, w, 4)
        gdt(w, w, y, x, 4)
        gdt(w, w, y, y, 4)
        gdt(w, w, y, z, 4)
        gdt(w, w, y, w, 4)
        gdt(w, w, z, x, 4)
        gdt(w, w, z, y, 4)
        gdt(w, w, z, z, 4)
        gdt(w, w, z, w, 4)
        gdt(w, w, w, x, 4)
        gdt(w, w, w, y, 4)
        gdt(w, w, w, z, 4)
        gdt(w, w, w, w, 4)
        gdt(r, r, r, r, 1)
        gdt(r, r, r, g, 2)
        gdt(r, r, r, b, 3)
        gdt(r, r, r, a, 4)
        gdt(r, r, g, r, 2)
        gdt(r, r, g, g, 2)
        gdt(r, r, g, b, 3)
        gdt(r, r, g, a, 4)
        gdt(r, r, b, r, 3)
        gdt(r, r, b, g, 3)
        gdt(r, r, b, b, 3)
        gdt(r, r, b, a, 4)
        gdt(r, r, a, r, 4)
        gdt(r, r, a, g, 4)
        gdt(r, r, a, b, 4)
        gdt(r, r, a, a, 4)
        gdt(r, g, r, r, 2)
        gdt(r, g, r, g, 2)
        gdt(r, g, r, b, 3)
        gdt(r, g, r, a, 4)
        gdt(r, g, g, r, 2)
        gdt(r, g, g, g, 2)
        gdt(r, g, g, b, 3)
        gdt(r, g, g, a, 4)
        gdt(r, g, b, r, 3)
        gdt(r, g, b, g, 3)
        gdt(r, g, b, b, 3)
        gdt(r, g, b, a, 4)
        gdt(r, g, a, r, 4)
        gdt(r, g, a, g, 4)
        gdt(r, g, a, b, 4)
        gdt(r, g, a, a, 4)
        gdt(r, b, r, r, 3)
        gdt(r, b, r, g, 3)
        gdt(r, b, r, b, 3)
        gdt(r, b, r, a, 4)
        gdt(r, b, g, r, 3)
        gdt(r, b, g, g, 3)
        gdt(r, b, g, b, 3)
        gdt(r, b, g, a, 4)
        gdt(r, b, b, r, 3)
        gdt(r, b, b, g, 3)
        gdt(r, b, b, b, 3)
        gdt(r, b, b, a, 4)
        gdt(r, b, a, r, 4)
        gdt(r, b, a, g, 4)
        gdt(r, b, a, b, 4)
        gdt(r, b, a, a, 4)
        gdt(r, a, r, r, 4)
        gdt(r, a, r, g, 4)
        gdt(r, a, r, b, 4)
        gdt(r, a, r, a, 4)
        gdt(r, a, g, r, 4)
        gdt(r, a, g, g, 4)
        gdt(r, a, g, b, 4)
        gdt(r, a, g, a, 4)
        gdt(r, a, b, r, 4)
        gdt(r, a, b, g, 4)
        gdt(r, a, b, b, 4)
        gdt(r, a, b, a, 4)
        gdt(r, a, a, r, 4)
        gdt(r, a, a, g, 4)
        gdt(r, a, a, b, 4)
        gdt(r, a, a, a, 4)
        gdt(g, r, r, r, 2)
        gdt(g, r, r, g, 2)
        gdt(g, r, r, b, 3)
        gdt(g, r, r, a, 4)
        gdt(g, r, g, r, 2)
        gdt(g, r, g, g, 2)
        gdt(g, r, g, b, 3)
        gdt(g, r, g, a, 4)
        gdt(g, r, b, r, 3)
        gdt(g, r, b, g, 3)
        gdt(g, r, b, b, 3)
        gdt(g, r, b, a, 4)
        gdt(g, r, a, r, 4)
        gdt(g, r, a, g, 4)
        gdt(g, r, a, b, 4)
        gdt(g, r, a, a, 4)
        gdt(g, g, r, r, 2)
        gdt(g, g, r, g, 2)
        gdt(g, g, r, b, 3)
        gdt(g, g, r, a, 4)
        gdt(g, g, g, r, 2)
        gdt(g, g, g, g, 2)
        gdt(g, g, g, b, 3)
        gdt(g, g, g, a, 4)
        gdt(g, g, b, r, 3)
        gdt(g, g, b, g, 3)
        gdt(g, g, b, b, 3)
        gdt(g, g, b, a, 4)
        gdt(g, g, a, r, 4)
        gdt(g, g, a, g, 4)
        gdt(g, g, a, b, 4)
        gdt(g, g, a, a, 4)
        gdt(g, b, r, r, 3)
        gdt(g, b, r, g, 3)
        gdt(g, b, r, b, 3)
        gdt(g, b, r, a, 4)
        gdt(g, b, g, r, 3)
        gdt(g, b, g, g, 3)
        gdt(g, b, g, b, 3)
        gdt(g, b, g, a, 4)
        gdt(g, b, b, r, 3)
        gdt(g, b, b, g, 3)
        gdt(g, b, b, b, 3)
        gdt(g, b, b, a, 4)
        gdt(g, b, a, r, 4)
        gdt(g, b, a, g, 4)
        gdt(g, b, a, b, 4)
        gdt(g, b, a, a, 4)
        gdt(g, a, r, r, 4)
        gdt(g, a, r, g, 4)
        gdt(g, a, r, b, 4)
        gdt(g, a, r, a, 4)
        gdt(g, a, g, r, 4)
        gdt(g, a, g, g, 4)
        gdt(g, a, g, b, 4)
        gdt(g, a, g, a, 4)
        gdt(g, a, b, r, 4)
        gdt(g, a, b, g, 4)
        gdt(g, a, b, b, 4)
        gdt(g, a, b, a, 4)
        gdt(g, a, a, r, 4)
        gdt(g, a, a, g, 4)
        gdt(g, a, a, b, 4)
        gdt(g, a, a, a, 4)
        gdt(b, r, r, r, 3)
        gdt(b, r, r, g, 3)
        gdt(b, r, r, b, 3)
        gdt(b, r, r, a, 4)
        gdt(b, r, g, r, 3)
        gdt(b, r, g, g, 3)
        gdt(b, r, g, b, 3)
        gdt(b, r, g, a, 4)
        gdt(b, r, b, r, 3)
        gdt(b, r, b, g, 3)
        gdt(b, r, b, b, 3)
        gdt(b, r, b, a, 4)
        gdt(b, r, a, r, 4)
        gdt(b, r, a, g, 4)
        gdt(b, r, a, b, 4)
        gdt(b, r, a, a, 4)
        gdt(b, g, r, r, 3)
        gdt(b, g, r, g, 3)
        gdt(b, g, r, b, 3)
        gdt(b, g, r, a, 4)
        gdt(b, g, g, r, 3)
        gdt(b, g, g, g, 3)
        gdt(b, g, g, b, 3)
        gdt(b, g, g, a, 4)
        gdt(b, g, b, r, 3)
        gdt(b, g, b, g, 3)
        gdt(b, g, b, b, 3)
        gdt(b, g, b, a, 4)
        gdt(b, g, a, r, 4)
        gdt(b, g, a, g, 4)
        gdt(b, g, a, b, 4)
        gdt(b, g, a, a, 4)
        gdt(b, b, r, r, 3)
        gdt(b, b, r, g, 3)
        gdt(b, b, r, b, 3)
        gdt(b, b, r, a, 4)
        gdt(b, b, g, r, 3)
        gdt(b, b, g, g, 3)
        gdt(b, b, g, b, 3)
        gdt(b, b, g, a, 4)
        gdt(b, b, b, r, 3)
        gdt(b, b, b, g, 3)
        gdt(b, b, b, b, 3)
        gdt(b, b, b, a, 4)
        gdt(b, b, a, r, 4)
        gdt(b, b, a, g, 4)
        gdt(b, b, a, b, 4)
        gdt(b, b, a, a, 4)
        gdt(b, a, r, r, 4)
        gdt(b, a, r, g, 4)
        gdt(b, a, r, b, 4)
        gdt(b, a, r, a, 4)
        gdt(b, a, g, r, 4)
        gdt(b, a, g, g, 4)
        gdt(b, a, g, b, 4)
        gdt(b, a, g, a, 4)
        gdt(b, a, b, r, 4)
        gdt(b, a, b, g, 4)
        gdt(b, a, b, b, 4)
        gdt(b, a, b, a, 4)
        gdt(b, a, a, r, 4)
        gdt(b, a, a, g, 4)
        gdt(b, a, a, b, 4)
        gdt(b, a, a, a, 4)
        gdt(a, r, r, r, 4)
        gdt(a, r, r, g, 4)
        gdt(a, r, r, b, 4)
        gdt(a, r, r, a, 4)
        gdt(a, r, g, r, 4)
        gdt(a, r, g, g, 4)
        gdt(a, r, g, b, 4)
        gdt(a, r, g, a, 4)
        gdt(a, r, b, r, 4)
        gdt(a, r, b, g, 4)
        gdt(a, r, b, b, 4)
        gdt(a, r, b, a, 4)
        gdt(a, r, a, r, 4)
        gdt(a, r, a, g, 4)
        gdt(a, r, a, b, 4)
        gdt(a, r, a, a, 4)
        gdt(a, g, r, r, 4)
        gdt(a, g, r, g, 4)
        gdt(a, g, r, b, 4)
        gdt(a, g, r, a, 4)
        gdt(a, g, g, r, 4)
        gdt(a, g, g, g, 4)
        gdt(a, g, g, b, 4)
        gdt(a, g, g, a, 4)
        gdt(a, g, b, r, 4)
        gdt(a, g, b, g, 4)
        gdt(a, g, b, b, 4)
        gdt(a, g, b, a, 4)
        gdt(a, g, a, r, 4)
        gdt(a, g, a, g, 4)
        gdt(a, g, a, b, 4)
        gdt(a, g, a, a, 4)
        gdt(a, b, r, r, 4)
        gdt(a, b, r, g, 4)
        gdt(a, b, r, b, 4)
        gdt(a, b, r, a, 4)
        gdt(a, b, g, r, 4)
        gdt(a, b, g, g, 4)
        gdt(a, b, g, b, 4)
        gdt(a, b, g, a, 4)
        gdt(a, b, b, r, 4)
        gdt(a, b, b, g, 4)
        gdt(a, b, b, b, 4)
        gdt(a, b, b, a, 4)
        gdt(a, b, a, r, 4)
        gdt(a, b, a, g, 4)
        gdt(a, b, a, b, 4)
        gdt(a, b, a, a, 4)
        gdt(a, a, r, r, 4)
        gdt(a, a, r, g, 4)
        gdt(a, a, r, b, 4)
        gdt(a, a, r, a, 4)
        gdt(a, a, g, r, 4)
        gdt(a, a, g, g, 4)
        gdt(a, a, g, b, 4)
        gdt(a, a, g, a, 4)
        gdt(a, a, b, r, 4)
        gdt(a, a, b, g, 4)
        gdt(a, a, b, b, 4)
        gdt(a, a, b, a, 4)
        gdt(a, a, a, r, 4)
        gdt(a, a, a, g, 4)
        gdt(a, a, a, b, 4)
        gdt(a, a, a, a, 4)
        #undef gdf

    private:
        // Member variables.
        T _data[N];
    };

    // Deduction guide.
    template<typename T>
    vec(const T&, const T&) -> vec<T, 2>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const T&, const T&) -> vec<T, 3>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const vec2<T>&) -> vec<T, 3>;

    // Deduction guide.
    template<typename T>
    vec(const vec2<T>&, const T&) -> vec<T, 3>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const T&, const T&, const T&) -> vec<T, 4>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const T&, const vec2<T>&) -> vec<T, 4>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const vec2<T>&, const T&) -> vec<T, 4>;

    // Deduction guide.
    template<typename T>
    vec(const vec2<T>&, const T&, const T&) -> vec<T, 4>;

    // Deduction guide.
    template<typename T>
    vec(const T&, const vec3<T>&) -> vec<T, 4>;

    // Deduction guide.
    template<typename T>
    vec(const vec3<T>&, const T&) -> vec<T, 4>;
}
